%YAML:1.0 # need to specify the file type at the top!

wheel:
  enabled: true
  type: "Wheel3DAng" #  Wheel2DAng, Wheel2DLin, Wheel2DCen, Wheel3DAng, Wheel3DLin, Wheel3DCen
  do_calib_dt: false
  do_calib_ext: false
  do_calib_int: false
  noise_w: 0.02
  noise_v: 0.05
  noise_p: 0.03
  init_cov_dt: 1e-4
  init_cov_ex_o: 1e-4
  init_cov_ex_p: 1e-3
  init_cov_in_b: 1e-3
  init_cov_in_r: 1e-3
  chi2_mult: 15
  timeoffset: 0.0             # Fine-tuned time offset to match 100 Hz rate, compensating for latency
  intrinsics: [0.13, 0.13, 0.61] # Using calibrated intrinsic values for wheel model accuracy
  reuse_of_information: false     # Maintains consistency with historical data for stability
  T_imu_wheel: 
    - [  1.0,  0.0,  0.0,  0.10 ]  # X (IMU: Downwards) corresponds to -Z (Wheel: Upwards)
    - [  0.0,  1.0,  0.0,  0.0  ]  # Y (IMU: Left) corresponds to X (Wheel: Forward)
    - [  0.0,  0.0,  1.0, -0.28 ]  # Z (IMU: Forward) corresponds to -Y (Wheel: Left)
    - [  0.0,  0.0,  0.0,  1.0  ]  # Homogeneous transformation matrix

  topic: "/joints/states"
